### ISSUE TITLE
Make failed

### ISSUE THREAD

**Issue by SG5** [bwoebi/php-uv#10]
After `make` i have a lot of errors
https://gist.github.com/SG5/176504c4f1608decaa2bbc767274958d

**Comment by bwoebi** [comment]
What OS and libuv versions are you compiling against?

**Comment by SG5** [comment]
I have `debian 8` under docker with `libuv0.10-dev Version: 0.10.28-6`

**Comment by bwoebi** [comment]
Uh, the code only works with libuv v1 … do not compile it against libuv v0.x

**Comment by SG5** [comment]
Thank you, with v1 compile without errors
