### ISSUE TITLE
Deleting the issue of breaking changes with no explanations?

### ISSUE THREAD

**Issue by mindaugasvcs** [bwoebi/php-uv#107]
Wow, wow, wow. Really?
Why are you wasting your time with this lib?

P.S.: This is my last question, no worries, won't bother you no more. [Narcissistic people](https://en.wikipedia.org/wiki/Narcissistic_personality_disorder).

**Comment by kelunik** [comment]
I've closed your previous issue as I felt is had been answered, I haven't deleted anything. 

I really don't like your tone here, so I'm closing this one as well.

**Comment by mindaugasvcs** [comment]
This does not change things much. You just distance yourself from the answer as I'm now left in the unknown as to what to do.

**Comment by mindaugasvcs** [comment]
Also you should not be a maintainer of this lib if my questions is out of your scope.

**Comment by kelunik** [comment]
You're using an open source project. You haven't bought a product with a support contract. I don't have the time to do the research for you. If you want to use an unreleased version, you'll need to do it yourself or pay someone to do it for you. In fact, the same is true for any released version. We usually provide changelogs, but there's neither a guarantee for that nor a guarantee that the changelog is complete.
