### ISSUE TITLE
Prompt API standard for PHP async IO?

### ISSUE THREAD

**Issue by ParkFramework** [bwoebi/php-uv#19]
Has is for event-loop
https://github.com/async-interop/event-loop

I need to IO, something like: `File::read(), File::write(), ...`

Thanks.

**Comment by bwoebi** [comment]
For files there are uv_fs* functions; e.g. https://github.com/bwoebi/php-uv#resource-uv_fs_openresource-loop-string-path-long-flag-long-mode-callable-callback

Have perhaps a look at an actual implementation of this (https://github.com/amphp/file/blob/amp_v2/lib/UvDriver.php and https://github.com/amphp/file/blob/amp_v2/lib/UvHandle.php) if the README is not explaining it good enough.

If you still have further questions, just ask in this issue (I'll close it as this is not an actual issue, but feel nevertheless free to ask in this issue).

**Comment by ParkFramework** [comment]
Yes, thank you.

I thought, there is PSR draft for async IO.
