### ISSUE TITLE
uv_timer_start - order of arguments

### ISSUE THREAD

**Issue by ParkFramework** [bwoebi/php-uv#24]
It will do as well in the library - `libuv: uv_timer_start(resource, callback,  timeout, repeat)`
http://docs.libuv.org/en/v1.x/timer.html#c.uv_timer_start

Thank.

**Comment by bwoebi** [comment]
Yeah, I'm aware. It would be a major breaking change though and thus not going to happen.

And anyway it's otherwise consistent: all of our uv_*() functions accepting callbacks are putting the callback as last argument.

**Comment by ParkFramework** [comment]
Ok :)
