### ISSUE TITLE
for the windows build, "php_sockets_le_socket" not found error reported

### ISSUE THREAD

**Issue by wanjochan** [bwoebi/php-uv#34]
as title

**Comment by wanjochan** [comment]
is there updated windows dll for download? (u know, the windows php extension build is painful!)

**Comment by kelunik** [comment]
@wanjochan One comment is enough, you don't need to open an issue, comment on the commit and here.

**Comment by wanjochan** [comment]
i am very sorry for that!

**Comment by kelunik** [comment]
Don't worry, just a little note.
