### ISSUE TITLE
Not implemented: uv_tcp_open(), uv_udp_open()

### ISSUE THREAD

**Issue by ParkFramework** [bwoebi/php-uv#36]
Very need functions:

`uv_tcp_open()`
http://docs.libuv.org/en/v1.x/tcp.html#c.uv_tcp_open

`uv_udp_open()`
http://docs.libuv.org/en/v1.x/udp.html#c.uv_udp_open

Is similar to implement  `uv_pipe_open()`
https://github.com/bwoebi/php-uv#void-uv_pipe_openresource-handle-long-pipe

Thank.

**Comment by bwoebi** [comment]
Just curious, what could it be used for? Commonly you'd just use bind+init, no?
Do you have a concrete example which would use it?

**Comment by ParkFramework** [comment]
Yes, we do not create sockets in PHP, we get sockets from `Systemd` as file descriptors `fd`
https://www.freedesktop.org/software/systemd/man/systemd.socket.html

Example: `uv_pipe_open($server, 3);` it looks like `fopen('php://fd/3', 'r+')`

**/etc/systemd/system/uv-echo.socket**
```
[Unit]
Description = UV Echo Socket

[Socket]
NoDelay      = yes
KeepAlive    = yes
ListenStream = 8080

[Install]
WantedBy = sockets.target
```

**/etc/systemd/system/uv-echo.service**
```
[Unit]
Description = UV Echo Server
BindsTo     = uv-echo.socket

[Service]
Type        = simple
NonBlocking = yes
ExecStart   = /usr/bin/php /var/www/test/uv-echo.php

[Install]
WantedBy = multi-user.target
```

**/var/www/test/uv-echo.php**
```php
<?php

$loop   = uv_default_loop();
$server = uv_pipe_init($loop, false);

echo "LOOP-START: $loop\n";

uv_pipe_open($server, 3); // THERE MUST BE - uv_tcp_open($server, 3);

echo "SERVER-OPEN: $server\n";

uv_listen($server, 128, function($server, $status) use($loop)
{
	if($status < 0)
	{
		echo "SERVER-ERROR: $server: $status\n";

		uv_close($server);
		return;
	}

	$client = uv_pipe_init($loop, false);
	uv_accept($server, $client);

	echo "CLIENT-ACCEPT: $client\n";

	uv_read_start($client, function($client, $length, $buffer)
	{
		if($length > 0)
		{
			echo "CLIENT-READ: $client: $length\n";
			uv_write($client, "ECHO: $buffer");
		}
		else
		{
			echo "CLIENT-CLOSE: $client\n";
			uv_close($client);
		}
	});
});

uv_run($loop);

echo "LOOP-STOP: $loop\n";
```

**Test 1**
``echo Hello| nc localhost 8080``

**Comment by bwoebi** [comment]
Right, thanks, that's the use case for pipes, but I'm not able to imagine where you'd get random tcp or udp socket fds?

**Comment by umbri** [comment]
@ParkFramework something very interesting.
@ParkFramework why not just use standart php sockets ? are there any advantages using systemd ?

**Comment by ParkFramework** [comment]
>  why not just use standart php sockets ? are there any advantages using systemd ?

Yes :)
The lazy launch of web services, monitored and logged with systemd, the ability to reboot without losing open sockets, configure sockets without changing PHP scripts, etc...

**Comment by umbri** [comment]
@ParkFramework intrigated, i will give it a try, Thank you

**Comment by bwoebi** [comment]
Implemented via 158f959f94ee4d7db8aa211e106303fc6e9f416f :-)

**Comment by umbri** [comment]
@ParkFramework I will be very thankful, if you provide more details about this, may be there are some pitfalls ?

**Comment by ParkFramework** [comment]
There everything is transparent, for TCP and UDP sockets, can be used `pipe` API, but `uv_tcp_open ()` and `uv_udp_open()` need for `libuv` to optimize work in kernel.

What exactly are you interested in?

**Comment by ParkFramework** [comment]
Failed compile

```
make
/bin/sh /opt/php-uv/libtool --mode=compile cc  -I. -I/opt/php-uv -DPHP_ATOM_INC -I/opt/php-uv/include -I/opt/php-uv/main -I/opt/php-uv -I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib  -DHAVE_CONFIG_H  -g -O2   -c /opt/php-uv/php_uv.c -o php_uv.lo 
libtool: compile:  cc -I. -I/opt/php-uv -DPHP_ATOM_INC -I/opt/php-uv/include -I/opt/php-uv/main -I/opt/php-uv -I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib -DHAVE_CONFIG_H -g -O2 -c /opt/php-uv/php_uv.c  -fPIC -DPIC -o .libs/php_uv.o
/opt/php-uv/php_uv.c: In function ‘php_uv_zval_to_valid_poll_fd’:
/opt/php-uv/php_uv.c:349:201: error: macro "strncmp" requires 3 arguments, but only 2 given
 ->wops->label, "PHP") && (!stream->orig_path || (strncmp(stream->orig_path, ZEND_STRL("php://std")) && strncmp(stream->orig_path, ZEND_STRL("php://fd")) && strncmp(stream->orig_path, ZEND_STRL("php://temp")))))) {
                                                                                                   ^
/opt/php-uv/php_uv.c:349:254: error: macro "strncmp" requires 3 arguments, but only 2 given
 cmp(stream->orig_path, ZEND_STRL("php://std")) && strncmp(stream->orig_path, ZEND_STRL("php://fd")) && strncmp(stream->orig_path, ZEND_STRL("php://temp")))))) {
                                                                                                   ^
/opt/php-uv/php_uv.c:349:309: error: macro "strncmp" requires 3 arguments, but only 2 given
 trncmp(stream->orig_path, ZEND_STRL("php://fd")) && strncmp(stream->orig_path, ZEND_STRL("php://temp")))))) {
                                                                                                       ^
Makefile:195: recipe for target 'php_uv.lo' failed
make: *** [php_uv.lo] Error 1

```

**Comment by bwoebi** [comment]
Fixed … I do not know why strcmp is ever defined as a macro, but oh well...

**Comment by umbri** [comment]
@ParkFramework Just in case :), when I start using sockets on php there where plenty pitfalls that no one say about :), like: file descriptors limits, __FD_SETSIZE, sysctl ...,  , from example all is simple and clear but in practice, you know what I am talking about :), for an expert this is obvious, but .. hey all of us start from something :)

**Comment by bwoebi** [comment]
@ParkFramework does it work fine? If yes, I'm going to release a new tag in a few days.

**Comment by ParkFramework** [comment]
> @ParkFramework does it work fine? If yes, I'm going to release a new tag in a few days.

Yes, but unfortunately the performance has not changed, the Pipe API and TCP API work equally fast on TCP sockets.

Thank!
