### ISSUE TITLE
uv_spawn() - must return code error, if fail start procces

### ISSUE THREAD

**Issue by ParkFramework** [bwoebi/php-uv#38]
> Otherwise, the negative error code corresponding to the reason it couldn’t spawn is returned.
http://docs.libuv.org/en/v1.x/process.html#c.uv_spawn

May be, after fail spawn, run `callback($resource, $code = $code_error, $sign = 0)`?
Thank.

**Comment by bwoebi** [comment]
The callback is `($processResource, $exit_status, $termsignal)`. That hasn't changed. But if the call to `uv_spawn()` itself is not zero, it will now return an integer error code.

**Comment by uasan** [comment]
Yes, fixed.

**Comment by uasan** [comment]
It may be better to throw exceptions - `throw new Exception(\uv_strerror($code), $code)`?

```PHP
<?php

$handle = uv_spawn($cmd);

if(!is_object($handle)) // ugly checking :)

```
Thank.

**Comment by bwoebi** [comment]
It might, I was avoiding that though, for backwards compatibility reasons.

Also, uv_spawn should usually not fail, except if the system is anyway out of resources or your arguments are bad.

**Comment by uasan** [comment]
Yes, but return mixed types, is bad design.

May be?
```PHP
<?php
$handle = uv_spawn($cmd);

if($handle->valid)
```
In practice, exceptions are more convenient...
