### ISSUE TITLE
is there updated windows dll for download (for #34)? 

### ISSUE THREAD

**Issue by wanjochan** [bwoebi/php-uv#41]
Is there updated windows dll for download? (u know, the windows php extension build is painful!)

https://github.com/bwoebi/php-uv/issues/34

**Comment by Gemorroj** [comment]
@bwoebi any updates for this issue?

**Comment by uasan** [comment]
@Gemorroj, change your avatar to something not shameful.

**Comment by wanjochan** [comment]
Nothing wrong with Lenin, especially for a Russian.
