### ISSUE TITLE
stream_copy_to_stream in libuv

### ISSUE THREAD

**Issue by uasan** [bwoebi/php-uv#47]
Hi.

`uv_write2()` - not work.
`uv_fs_sendfile()` - for only file system

How to send socket/pipe to another socket/pipe?

Thank.

**Comment by bwoebi** [comment]
uv_write2() is used for transmission of file descriptors to another process. (i.e. not the contents, but the fd itself)
uv_fs_sendfile() is a limited version (which also will run in the thread pool).

There is actually no way within libuv to support splice(2) or sendfile(2) on fds not being actual file handles.
If you desire to be able this, you need to open a feature request upstream in libuv itself.

Closing this issue for now - once libuv implements native fd-to-fd copying, we may reopen this issue.

**Comment by uasan** [comment]
> uv_write2() is used for transmission of file descriptors to another process. (i.e. not the contents, but the fd itself)

I spent a lot of time to pass the fd, but can not send fd (IPC = 1).
``` PHP
<?php
uv_write2($fd_1, 'BUF', $fd_2, function(){...})
```

`$fd_1` - reading only 'BUF' string, not accepted `$fd_2`

Have you seen any good working examples?
Thank.

**Comment by uasan** [comment]
Wow, i done! :)

**Comment by bwoebi** [comment]
You mean, you've achieved transferring a file descriptor between two processes?

**Comment by uasan** [comment]
> You mean, you've achieved transferring a file descriptor between two processes?

Yes.
