### ISSUE TITLE
Assertion `loop->watchers[w->fd] == w

### ISSUE THREAD

**Issue by arnaud-lb** [bwoebi/php-uv#49]
libuv doesn't support having multiple `uv_poll_t` with the same file descriptor.

Hence, php-uv doesn't support doing `uv_poll_init` + `uv_poll_start` multiple times on the same stream, or on streams that have the same underlying fd.

Trying to do so results in this:

    Assertion `loop->watchers[w->fd] == w

It would be great if php-uv had a way to get the underlying file descriptor of a stream. I added a `uv_get_fdno()` on my personal fork, and it allowed me to work around this issue: https://github.com/arnaud-lb/php-uv/commit/a7676b79dd7548ff33f6bc1d08fa36d4d0683b1c

**Comment by kelunik** [comment]
@arnaud-lb I'd recommend to just use a library that cares about that, see https://github.com/amphp/amp.

**Comment by arnaud-lb** [comment]
I stumbled on this while writing a php-uv driver for reactphp, so nobody can care of if for me, and I've found that I couldn't take care of it either, hence this issue :)

I already took a look at amp's driver for inspiration, and while it seems to avoid creating multiple UVPools for the same stream, it doesn't prevent from creating multiple UVPools for the same OS fd.

Creating multiple UVPools for the same OS fd is unavoidable from a driver perspective in the following cases:
 - When different streams have the same underlying fd
 - When closing a monitored stream, it's possible that newly created streams get assigned the same fd number. Then, monitoring the new stream will create a new UVPool with the same fd as an existing UVPool

**Comment by uasan** [comment]
> It is not okay to have multiple active poll handles for the same socket, this can cause libuv to busyloop or otherwise malfunction.
http://docs.libuv.org/en/v1.x/poll.html

You can call a lot of event handlers on one poll.

**Comment by kelunik** [comment]
Your second case is always a programming error. Not cancelling the watcher will leak memory.

The first case is actually valid and might be hit in case one opens STDERR multiple times. Other than for STDERR I don't see much potential for that to happen. Do you have other cases?

See also https://3v4l.org/OvHUJ.

**Comment by arnaud-lb** [comment]
I believe that good libraries should at least attempt to prevent coding errors, and to make debugging easier.

Letting a reactphp or amp user see his php process crash with a `Assertion loop->watchers[w->fd] == w` message is not great.

It may not be the role of php-uv to prevent this, but if php-uv could provide tools to prevent it (e.g. a function to expose fd numbers from streams), it would be awesome :) A driver could easily catch the two mentioned cases and display a _nice_ explanative exception.

> The first case is actually valid and might be hit in case one opens STDERR multiple times. Other than for STDERR I don't see much potential for that to happen. Do you have other cases?

I can think at least of streams that happen to proxy/wrap actual streams (e.g. a user stream).

**Comment by bwoebi** [comment]
There is no real way to catch a C-level assertion failure thrown by libuv, apart from overloading the libc handlers. Which by itself is very hacky and possibly unreliable. I prefer not doing this on an a project targeting multiple different systems.

It should be possible to add some sort of expensive debug mode, which checks for validity upon creation/activation, by verifying the existing handles.

**Comment by kelunik** [comment]
@bwoebi What do we do with that?

> The first case is actually valid and might be hit in case one opens STDERR multiple times. Other than for STDERR I don't see much potential for that to happen. Do you have other cases?

**Comment by bwoebi** [comment]
@kelunik well, that said debug mode would discover it then (by file descriptor internally) … but you cannot handle that from within PHP, that's right. But really, it's only the `php://` streams which expose such weird behavior. All other fds cannot be referenced by two different resources.

**Comment by arnaud-lb** [comment]
> There is no real way to catch a C-level assertion failure thrown by libuv, apart from overloading the libc handlers

Yes, I was not advocating that :) Giving the user-space a way to find the fd of a PHP stream is more than enough to implement proper guards/errors in react/amp.

**Comment by arnaud-lb** [comment]
A simple function like that works with all PHP streams accepted by php-uv: https://github.com/arnaud-lb/php-uv/commit/a7676b79dd7548ff33f6bc1d08fa36d4d0683b1c

**Comment by kelunik** [comment]
@bwoebi I guess we have the same issue with `php://fd/42`, so it's basically any FD. :P

**Comment by bwoebi** [comment]
For debugging purposes the next version of php-uv is going to expose the fd via its debuginfo.
Regarding the assertion, it will hopefully disappear within https://github.com/libuv/libuv/pull/2686, when uv_poll_start() is going to report UV_EEXIST instead. (PHP uv will emit a warning as it is right now.)

**Comment by CharlotteDunois** [comment]
@bwoebi Exposing the FD via the debug info might be of limited use. I would add an utility function that returns the file descriptor from a PHP stream. I would argue that this utility function should be in PHP core, however a PHP internals developer said some years ago that this change would require a RFC. Even with a passing RFC, this utility would only go into the next minor version, so previous version won't profit from the new function. So I would expose that function instead in php-uv for now, so previous next-minor (<= 7.4) will profit.

The function `uv_pipe_open` requires a file descriptor, so that function would be required anyway if you want to open std* in a child process as libuv pipe - unless I've missed some magic. Otherwise that function should accept PHP streams (as they're exposed in the CLI SAPI through constants), too.

**Comment by bwoebi** [comment]
@CharlotteDunois https://github.com/bwoebi/php-uv/commit/0b40ad9f512953c1c5c00d9637732891516a703c - it now accepts resources as well.

**Comment by arnaud-lb** [comment]
@bwoebi: Libuv starting to return UV_EEXISTS is great! Something like https://github.com/arnaud-lb/php-uv/commit/a7676b79dd7548ff33f6bc1d08fa36d4d0683b1c would still be an improvement, by allowing `php-uv` users to prevent that from happening.

**Comment by CharlotteDunois** [comment]
@arnaud-lb I would prefer if the function would not emit a warning by itself, but instead return `null` or `false`. If the user wishes to have a warning or an exception, they can emit or throw it themself for the desired behaviour. The function should be side effect-free by itself (in terms of PHP error handling mechanism), since all the function does is extracting a file descriptor and has no side effects (i.e. polling the fd).

**Comment by bwoebi** [comment]
@CharlotteDunois I agree and I intend to have it return the error instead.

**Comment by enumag** [comment]
bump, just got this again

```
php: src/unix/core.c:896: uv__io_stop: Assertion `loop->watchers[w->fd] == w' failed.
```

**Comment by enumag** [comment]
bump

**Comment by enumag** [comment]
This seems to be the same as #81 so I think it can be closed now.

**Comment by bwoebi** [comment]
Well possible, let me close it for now - if it ever happens again (with a new libuv shared object), open a new ticket then.
