### ISSUE TITLE
uv_fs_event_init - Unable to watch directory

### ISSUE THREAD

**Issue by amitabhkant** [bwoebi/php-uv#50]
I am trying to get fsevevnt.php code working on Debian with PHP7 . I can't seem to make it work as it exits immediately on running the code . My assumption is that uv_run() should keep it in running listening for any changes to the directory supplied as second parameter. Am I missing something?

P.S. Apologies for the blank report earlier. Somehow submitted without completing the question.

**Comment by kelunik** [comment]
Uhm... what's your question or request?

**Comment by amitabhkant** [comment]
Just updated the original question. Had clicked the submit button  too soon.

**Comment by amitabhkant** [comment]
I tried using the function uv_last_error() to see if there were any error thrown, and strangely php exited with "PHP Fatal error:  Uncaught Error: Call to undefined function uv_last_error()". So not sure what is happening here. 

The environment is as follows:
Debian 8.9, PHP 7.0.22, libuv 1.9  with php-uv extension correctly loaded as I can run the timer and tcp_bind test perfectly. "make test" clears the fsevent test.

**Comment by amitabhkant** [comment]
Another update: 
To make sure that my libuv was working on the system correctly (Debian running as guest within MacOS host using virtualbox), I compiled a basic c code for monitoring directories using libuv from this page: [https://github.com/nikhilm/uvbook/blob/master/code/onchange/main.c](url)  . 

Compiled it using `gcc -Wall -o hw hw.c /usr/local/lib/libuv.a -pthread` .  

Using the compiled application, I am able to watch over a directory without any problems. I am not well versed with either C or PHP extension process to debug **php_uv.c**, so at loss on how to debug the issue at hand.

**Comment by bwoebi** [comment]
The issue of this example was that it wasn't holding a reference to the object returned by uv_fs_event_init().
As long as you persist that reference, the watcher will be held alive.

I've fixed the example to properly reflect that, thanks :-)
