### ISSUE TITLE
Build failure in ubuntu.

### ISSUE THREAD

**Issue by itskevinsam** [bwoebi/php-uv#52]
Tried to build the bundle (from master) for php 7.1 Make dumps and stops after.

In file included from /etc/php/7.1/builds/php-uv/php_uv.h:33:0,
                 from /etc/php/7.1/builds/php-uv/php_uv.c:21:
/usr/include/uv.h:1715:15: note: expected ‘uv_fs_poll_cb {aka void (*)(struct uv_fs_poll_s *, int,  const struct stat *, const struct stat *)}’ but argument is of type ‘void (*)(uv_fs_poll_t *, int,  const int *, const int *) {aka void (*)(struct uv_fs_poll_s *, int,  const int *, const int *)}’
 UV_EXTERN int uv_fs_poll_start(uv_fs_poll_t* handle,
               ^
Makefile:195: recipe for target 'php_uv.lo' failed
make: *** [php_uv.lo] Error 1

more log.

In file included from /etc/php/7.1/builds/php-uv/php_uv.h:33:0,
                 from /etc/php/7.1/builds/php-uv/php_uv.c:21:
/usr/include/uv.h:1211:15: note: expected ‘uv_async_cb {aka void (*)(struct uv_async_s *, int)}’ but argument is of type ‘void (*)(uv_async_t *) {aka void (*)(struct uv_async_s *)}’
 UV_EXTERN int uv_async_init(uv_loop_t*, uv_async_t* async,
               ^
/etc/php/7.1/builds/php-uv/php_uv.c: In function ‘zif_uv_fs_readdir’:
/etc/php/7.1/builds/php-uv/php_uv.c:5729:19: error: ‘UV_FS_SCANDIR’ undeclared (first use in this function)
  php_uv_fs_common(UV_FS_SCANDIR, INTERNAL_FUNCTION_PARAM_PASSTHRU);
                   ^
/etc/php/7.1/builds/php-uv/php_uv.c: In function ‘zif_uv_fs_scandir’:
/etc/php/7.1/builds/php-uv/php_uv.c:5737:22: error: ‘UV_FS_SCANDIR’ undeclared (first use in this function)
     php_uv_fs_common(UV_FS_SCANDIR, INTERNAL_FUNCTION_PARAM_PASSTHRU);
                      ^
/etc/php/7.1/builds/php-uv/php_uv.c: In function ‘zif_uv_fs_event_init’:
/etc/php/7.1/builds/php-uv/php_uv.c:5772:40: error: too few arguments to function ‘uv_fs_event_init’
  PHP_UV_INIT_UV_EX(uv, uv_fs_event_ce, uv_fs_event_init);
                                        ^
/etc/php/7.1/builds/php-uv/php_uv.c:157:7: note: in definition of macro ‘PHP_UV_INIT_UV_EX’
   r = cb(&loop->loop, (void *) &_uv->uv.handle, ##__VA_ARGS__); \
       ^
In file included from /etc/php/7.1/builds/php-uv/php_uv.h:33:0,
                 from /etc/php/7.1/builds/php-uv/php_uv.c:21:
/usr/include/uv.h:1813:15: note: declared here
 UV_EXTERN int uv_fs_event_init(uv_loop_t* loop, uv_fs_event_t* handle,
               ^
/etc/php/7.1/builds/php-uv/php_uv.c:5776:10: warning: implicit declaration of function ‘uv_fs_event_start’ [-Wimplicit-function-declaration]
  error = uv_fs_event_start(&uv->uv.fs_event, php_uv_fs_event_cb, path->val, flags);
          ^
/etc/php/7.1/builds/php-uv/php_uv.c: In function ‘zif_uv_fs_poll_start’:
/etc/php/7.1/builds/php-uv/php_uv.c:6070:44: warning: passing argument 2 of ‘uv_fs_poll_start’ from incompatible pointer type [-Wincompatible-pointer-types]
  error = uv_fs_poll_start(&uv->uv.fs_poll, php_uv_fs_poll_cb, (const char*)path->val, interval);
                                            ^
In file included from /etc/php/7.1/builds/php-uv/php_uv.h:33:0,
                 from /etc/php/7.1/builds/php-uv/php_uv.c:21:
/usr/include/uv.h:1715:15: note: expected ‘uv_fs_poll_cb {aka void (*)(struct uv_fs_poll_s *, int,  const struct stat *, const struct stat *)}’ but argument is of type ‘void (*)(uv_fs_poll_t *, int,  const int *, const int *) {aka void (*)(struct uv_fs_poll_s *, int,  const int *, const int *)}’
 UV_EXTERN int uv_fs_poll_start(uv_fs_poll_t* handle,

@bwoebi

**Comment by bwoebi** [comment]
Is that the whole error message? This is a _note_, that should not fail the build by itself.

**Comment by bwoebi** [comment]
You are building against a pre-v1.0.0 version of libuv (possibly 0.10?), which is not supported. Install a newer libuv build please.
