### ISSUE TITLE
Can't install ext

### ISSUE THREAD

**Issue by kivlara** [bwoebi/php-uv#6]
Hi,
Thank you for your work.

1. How can I install this ?? What version of libuv I need to install to use it ??
```chobie/php-uv``` I was able to install without any issues using ```apt-get install libuv0.10-dev```
but this one I can't figure how to install, I try to install using libuv 1.7.5 (last) but when I try to ```make``` 
```bwoebi/php-uv``` I get errors. I suppose this is because of wrong libuv version.

Please help me.

**Comment by bwoebi** [comment]
What errors did you get?

**Comment by kivlara** [comment]
Here is all steps I am doing:
```
git clone -b v1.x https://github.com/libuv/libuv.git
git checkout a8c1136de2cabf25b143021488cbaab05834daa8
sh autogen.sh
./configure
make
make install

git clone --recursive https://github.com/bwoebi/php-uv.git
cd php-uv/
phpize
./configure
make
```
ERROR is very big so: 
```http://pastebin.com/36rJFpzz```

**Comment by bwoebi** [comment]
Uhm… you are compiling this extension against 5.6? Nah, for 5.6, use chobie's old repository.
This extension is PHP 7.0 only.

**Comment by kivlara** [comment]
Thank you. Now All clear!
