### ISSUE TITLE
Windows Builds

### ISSUE THREAD

**Issue by CharlotteDunois** [bwoebi/php-uv#63]
The website daverandom.com is down unfortunately - is there any way to get a uv extension dll? PECL releases seems to be unable to build php-uv (the logs say something about invalid configuration).

Trying to build a shared dll myself leads to the same errors as PECL. I'm trying to build it for PHP 7.2.14 x64 VC15 ZTS on Windows 7 x64.

Do you have any instructions to build it or can you arrange that PECL builds it successfully?

**Comment by CharlotteDunois** [comment]
ping @bwoebi

**Comment by clue** [comment]
The way I understand the referenced tickets, building on Windows should work again? This is great news.

Additionally, are there any ready-to-use DLLs available for the average Windows users (i.e. without manually compiling this extension)? The documentation still links to a broken site for Windows builds (https://github.com/bwoebi/php-uv#windows). It looks like most PECL extensions list DLLs on their PECL page, but this does not seem to apply this UV extension (https://pecl.php.net/package/uv).

It's my understanding making these DLLs available more prominently would certainly help adoption on Windows platform :+1:

**Comment by CharlotteDunois** [comment]
PECL usually builds DLLs and then they're linked on the page. If PECL doesn't build DLL, then these won't be linked. But yes, building on Windows works again. I've compiled a DLL for testing purposes myself.

@bwoebi Could you please check that PECL builds DLLs? Thanks!

**Comment by bwoebi** [comment]
I have no idea why https://windows.php.net/downloads/pecl/releases/uv/ doesn't list it. And no idea either what I can do about it...

**Comment by bwoebi** [comment]
Okay, now it's there at https://windows.php.net/downloads/pecl/releases/uv/0.2.4/ :-)

**Comment by CharlotteDunois** [comment]
@bwoebi Thank you!
