### ISSUE TITLE
memory leak

### ISSUE THREAD

**Issue by kivlara** [bwoebi/php-uv#7]
Sorry for this post but may be someone can help me!

here is the code:
```
$arr = [];
for($i = 0; $i < 1000; $i++)
{
    $b = uv_pipe_init(uv_default_loop(), 0);
    uv_pipe_connect($b, "/tmp/redis.sock", function($a, $b)
    {
        print("connected\n");
    });

    $arr[] = $b;
}

uv_run();
```
after 5 sec: i close all connections and check ```memory_get_usage(true);```
I see that memory is not free 

```
    foreach($arr as $pipe)
    {
        uv_close($pipe, function($pipe)
        {
            uv_unref($pipe);
            print("close\n");
        });
    }
```

Can someone help me ??

**Comment by bwoebi** [comment]
yep… do not use the `true` parameter… is it better then? After all that's the real memory and this is heavily dependent on the internal allocator not reflecting the memory the actually alive variables of your code are taking up.

**Comment by kivlara** [comment]
omg, this really worked! thank you.
But how about second question ?? (issue: https://github.com/bwoebi/php-uv/issues/6)

Thank you.

**Comment by bwoebi** [comment]
As said, I need the errors to figure out what's going wrong… I try to keep this lib up with the most recent version of libuv...
