### ISSUE TITLE
Missing function to stop watching a filesystem entry

### ISSUE THREAD

**Issue by CharlotteDunois** [bwoebi/php-uv#70]
php-uv exposes the function `uv_fs_event_init` to start watching a filesystem entry (file or directory) for changes, however there is no function to stop a filesystem entry from being watched.

The TODO is still in the source code.
https://github.com/bwoebi/php-uv/blob/63fa7f1609f6989aa5abf938c465643dd8a120bb/php_uv.c#L5813-L5814

In libuv the handle can be stopped through <http://docs.libuv.org/en/v1.x/fs_event.html#c.uv_fs_event_stop>.

**Comment by CharlotteDunois** [comment]
@bwoebi status?

**Comment by WyriHaximus** [comment]
Any updates on this?

**Comment by bwoebi** [comment]
You should use uv_close() here. Yes, libuv exposes uv_fs_event_start() and uv_fs_event_stop(), but we aren't exposing either, because there's no benefit (no state which is persisted or similar) - at least currently.

uv_fs_event_init() is init+start and uv_close() is stop+close.
