### ISSUE TITLE
Using UV_IGNORE in uv_spawn

### ISSUE THREAD

**Issue by CharlotteDunois** [bwoebi/php-uv#73]
The [libuv documentation](http://docs.libuv.org/en/v1.x/guide/processes.html#child-process-i-o) has an example that specifies `flags` of the stdio field to ignore to `UV_IGNORE` to skip over it, however this extension starts in `uv_spawn` with 0 and simply increments the key (ignoring the given array indexes).

Would the only way to not use a stdio field be by explicitely mapping to `/dev/null` (which is what libuv does behind the scene)?

**Comment by CharlotteDunois** [comment]
@bwoebi status?

**Comment by bwoebi** [comment]
I think we should be explicit, but now you can actually use `$ignored_stdio_pipe = uv_stdio_new();` in the array.
