### ISSUE TITLE
Missing arginfo when installed on PHP 8

### ISSUE THREAD

**Issue by kelunik** [bwoebi/php-uv#85]
PHP Warning:  Missing arginfo for uv_loop_new() in Unknown on line 0
PHP Warning:  Missing arginfo for uv_default_loop() in Unknown on line 0
PHP Warning:  Missing arginfo for uv_stdio_new() in Unknown on line 0
PHP Warning:  Missing arginfo for uv_rwlock_init() in Unknown on line 0
PHP Warning:  Missing arginfo for uv_mutex_init() in Unknown on line 0
PHP Warning:  Missing arginfo for uv_tty_set_mode() in Unknown on line 0
PHP Warning:  Missing arginfo for uv_tty_reset_mode() in Unknown on line 0
PHP Warning:  Missing arginfo for uv_loadavg() in Unknown on line 0
PHP Warning:  Missing arginfo for uv_uptime() in Unknown on line 0
PHP Warning:  Missing arginfo for uv_cpu_info() in Unknown on line 0
PHP Warning:  Missing arginfo for uv_interface_addresses() in Unknown on line 0
PHP Warning:  Missing arginfo for uv_get_free_memory() in Unknown on line 0
PHP Warning:  Missing arginfo for uv_get_total_memory() in Unknown on line 0
PHP Warning:  Missing arginfo for uv_hrtime() in Unknown on line 0
PHP Warning:  Missing arginfo for uv_exepath() in Unknown on line 0
PHP Warning:  Missing arginfo for uv_cwd() in Unknown on line 0
PHP Warning:  Missing arginfo for uv_resident_set_memory() in Unknown on line 0

**Comment by bwoebi** [comment]
(self-note: happens with debug build only)
