### ISSUE TITLE
The 'uv_pipe_connect' not right, expected callback signature actaully passed in reverse

### ISSUE THREAD

**Issue by techno-express** [bwoebi/php-uv#86]
The `uv_pipe_connect` callback coming thru in reverse order, `int` $status, being pass first, then `UVPipe` object

 The example `pipe_bind_connect.php` errors on Windows and Linux with:
`PHP Warning:  uv_write() expects parameter 1 to be UVTcp, UVPipe, integer given in ../examples/uv/pipe_bind_connect.php on line 27`

Temporary switching around, the example works as expected.
`uv_pipe_connect($b, PIPE_PATH, function($pipe, $status)` 
to `uv_pipe_connect($b, PIPE_PATH, function($status, $pipe)`

**Comment by CharlotteDunois** [comment]
It was changed with commit e76ac0dccb7908181ee715326e4f8061b77712f6. Part of the callback signature refactor for v0.3.

**Comment by techno-express** [comment]
what's the reasoning for that when everything is still object first? I figure it's a bug, no reason for having status first. The signature for v0.3 show otherwise, callback handle still first.

**Comment by CharlotteDunois** [comment]
Status first is current pecl state v0.2.4 - the new callback signature with object first affects v0.3.0 (current master, no release).

**Comment by techno-express** [comment]
>  the new callback signature with object first affects v0.3.0 (current master, no release).

What? That is you talking about, that is what is stated, I'm referencing v0.3. I see current master. 

https://github.com/bwoebi/php-uv/blob/0b40ad9f512953c1c5c00d9637732891516a703c/php_uv.c#L1518

https://github.com/bwoebi/php-uv/blob/0b40ad9f512953c1c5c00d9637732891516a703c/php_uv.c#L4727

Did you miss I'm referencing the example?
What commit you see the example otherwise? 

Have you run the examples then and now? 

What commit where `uv_pipe_connect` or anything where status is first?

**Comment by CharlotteDunois** [comment]
Any php-uv build previous to commit e76ac0dccb7908181ee715326e4f8061b77712f6 has the status first, which includes all pecl builds of the extension until to this point (v0.2.4).

Here's a build output of the example, adapted to `var_dump` the given callback function arguments.

Latest version installed through PECL:
```
php-uv version: 0.2.4
/home/circleci/project/run_example_pipe_bind.php:21:
array(2) {
  [0] =>
  int(0)
  [1] =>
  class UVPipe#4 (0) {
  }
}
```

Latest version build from source:
```
php-uv version: 0.3.0
/home/circleci/project/run_example_pipe_bind.php:21:
array(2) {
  [0] =>
  class UVPipe#4 (0) {
  }
  [1] =>
  int(0)
}
```

**Comment by techno-express** [comment]
I see the example then used ` function($a,$b)`, now `function($pipe, $status) `
