### ISSUE TITLE
Put php-uv on PECL

### ISSUE THREAD

**Issue by joshdifabio** [bwoebi/php-uv#9]
Have you considered putting uv on PECL?

**Comment by bwoebi** [comment]
Probably not a bad idea... Have to figure out how it works…

**Comment by ParkFramework** [comment]
Need "tagged" released

https://forum.remirepo.net/viewtopic.php?id=3505

**Comment by ParkFramework** [comment]
Thanks!

**Comment by bwoebi** [comment]
Done in the meanwhile…
